/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class MenuUtama extends javax.swing.JFrame {
    String nama = Login.getU_nama();

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        userJl.setText(nama);
    }
    
    public void hakAksesPemilik(){
        barangBT.setEnabled(false);
        pembelianBT.setEnabled(false);
        suplierBT.setEnabled(false);
        penjualanBT.setEnabled(false);
        xmaster.setEnabled(false);
        xtrans.setEnabled(false);
    }
    
    public void hakAksesKasir(){
        barangBT.setEnabled(false);
        xmaster.setEnabled(false);
        xpembelian.setEnabled(false);
        xpengguna.setEnabled(false);
        xlappembelian.setEnabled(false);
        barangx.setEnabled(false);
        pembelianBT.setEnabled(false);
        suplierBT.setEnabled(false);
    }
    
    public void hakAksesPersediaan(){
        xpengguna.setEnabled(false);
        xpenjualan.setEnabled(false);
        penjualanx.setEnabled(false);
        penjualanBT.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        loginJL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        userJl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        logoutBT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        barangBT = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        penjualanBT = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        pembelianBT = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        suplierBT = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        xlogout = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        xmaster = new javax.swing.JMenu();
        xbarang = new javax.swing.JMenuItem();
        xsuplier = new javax.swing.JMenuItem();
        xtrans = new javax.swing.JMenu();
        xpembelian = new javax.swing.JMenuItem();
        xpenjualan = new javax.swing.JMenuItem();
        xlap = new javax.swing.JMenu();
        barangx = new javax.swing.JMenuItem();
        xlappembelian = new javax.swing.JMenuItem();
        penjualanx = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        xpengguna = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TB Umar Jaya");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(237, 237, 244));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Login Terakhir : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 130, -1));

        loginJL.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        loginJL.setText("jLabel4");
        jPanel1.add(loginJL, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 350, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("SELAMAT DATANG DI APLIKASI");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 380, -1));

        userJl.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        userJl.setText("jLabel1");
        jPanel1.add(userJl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("TOKO BANGUNAN UMAR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Nama User : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, -1, -1));

        jToolBar1.setBackground(new java.awt.Color(255, 102, 102));
        jToolBar1.setRollover(true);

        logoutBT.setBackground(new java.awt.Color(204, 0, 0));
        logoutBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        logoutBT.setForeground(new java.awt.Color(255, 255, 255));
        logoutBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logout.png"))); // NOI18N
        logoutBT.setText("Logout");
        logoutBT.setToolTipText("Klik untuk logout pengguna");
        logoutBT.setFocusable(false);
        logoutBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTActionPerformed(evt);
            }
        });
        jToolBar1.add(logoutBT);
        jToolBar1.add(jSeparator1);

        barangBT.setBackground(new java.awt.Color(204, 0, 0));
        barangBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        barangBT.setForeground(new java.awt.Color(255, 255, 255));
        barangBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/barangg.png"))); // NOI18N
        barangBT.setText("Barang");
        barangBT.setToolTipText("Klik untuk menambahkan data barang");
        barangBT.setFocusable(false);
        barangBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barangBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barangBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangBTActionPerformed(evt);
            }
        });
        jToolBar1.add(barangBT);
        jToolBar1.add(jSeparator2);

        penjualanBT.setBackground(new java.awt.Color(204, 0, 0));
        penjualanBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        penjualanBT.setForeground(new java.awt.Color(255, 255, 255));
        penjualanBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/shopp.png"))); // NOI18N
        penjualanBT.setText("Penjualan");
        penjualanBT.setToolTipText("klik untuk menambahkan data transaksi penjualan");
        penjualanBT.setFocusable(false);
        penjualanBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        penjualanBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        penjualanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanBTActionPerformed(evt);
            }
        });
        jToolBar1.add(penjualanBT);
        jToolBar1.add(jSeparator3);

        pembelianBT.setBackground(new java.awt.Color(204, 0, 0));
        pembelianBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        pembelianBT.setForeground(new java.awt.Color(255, 255, 255));
        pembelianBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pembeliann.png"))); // NOI18N
        pembelianBT.setText("Pembelian");
        pembelianBT.setToolTipText("klik untuk menambahkan data transaksi pembelian");
        pembelianBT.setFocusable(false);
        pembelianBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pembelianBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pembelianBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianBTActionPerformed(evt);
            }
        });
        jToolBar1.add(pembelianBT);
        jToolBar1.add(jSeparator4);

        suplierBT.setBackground(new java.awt.Color(204, 0, 0));
        suplierBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        suplierBT.setForeground(new java.awt.Color(255, 255, 255));
        suplierBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/suplayer.png"))); // NOI18N
        suplierBT.setText("Supplier");
        suplierBT.setToolTipText("klik untuk menambahkan data supplier");
        suplierBT.setFocusable(false);
        suplierBT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suplierBT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suplierBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suplierBTActionPerformed(evt);
            }
        });
        jToolBar1.add(suplierBT);
        jToolBar1.add(jSeparator5);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 153));

        jMenu1.setText("File");

        xlogout.setText("Logout");
        xlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(xlogout);
        jMenu1.add(jSeparator6);

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        xmaster.setText("Master");

        xbarang.setText("Barang");
        xbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xbarangActionPerformed(evt);
            }
        });
        xmaster.add(xbarang);

        xsuplier.setText("Supplier");
        xsuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xsuplierActionPerformed(evt);
            }
        });
        xmaster.add(xsuplier);

        jMenuBar1.add(xmaster);

        xtrans.setText("Transaksi");

        xpembelian.setText("Pembelian");
        xpembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpembelianActionPerformed(evt);
            }
        });
        xtrans.add(xpembelian);

        xpenjualan.setText("Penjualan");
        xpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpenjualanActionPerformed(evt);
            }
        });
        xtrans.add(xpenjualan);

        jMenuBar1.add(xtrans);

        xlap.setText("Laporan");

        barangx.setText("Barang");
        barangx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangxActionPerformed(evt);
            }
        });
        xlap.add(barangx);

        xlappembelian.setText("Pembelian");
        xlappembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlappembelianActionPerformed(evt);
            }
        });
        xlap.add(xlappembelian);

        penjualanx.setText("Penjualan");
        penjualanx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanxActionPerformed(evt);
            }
        });
        xlap.add(penjualanx);

        jMenuBar1.add(xlap);

        jMenu5.setText("Utility");

        xpengguna.setText("Data Pengguna");
        xpengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xpenggunaActionPerformed(evt);
            }
        });
        jMenu5.add(xpengguna);

        jMenuItem11.setText("Ganti Password");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Help");

        jMenuItem2.setText("Tentang Aplikasi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jToolBar1.getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void xlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlogoutActionPerformed
        // TODO add your handling code here:
        Login LG=new Login();
        LG.setLocationRelativeTo(null);
        LG.setVisible(true);
        dispose();
    }//GEN-LAST:event_xlogoutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        DateFormat tgl=new SimpleDateFormat("dd MMMM yyyy");
        DateFormat waktu=new SimpleDateFormat("HH:mm:ss");
        String htgl=tgl.format(Calendar.getInstance().getTime());
        String hwaktu=waktu.format(Calendar.getInstance().getTime());
        loginJL.setText(htgl+" - "+hwaktu); 
    }//GEN-LAST:event_formWindowActivated

    private void barangxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangxActionPerformed
        // TODO add your handling code here:
        lapBarang LB=new lapBarang();
        LB.setLocationRelativeTo(null);
        LB.setVisible(true);
    }//GEN-LAST:event_barangxActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon("src/gambar/kredit.png");
        setIconImage(img.getImage());
    }//GEN-LAST:event_formWindowOpened

    private void xlappembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xlappembelianActionPerformed
        // TODO add your handling code here:
        lapBeli LB=new lapBeli();
        LB.setLocationRelativeTo(null);
        LB.setVisible(true);
    }//GEN-LAST:event_xlappembelianActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        Ubah UB=new Ubah();
        UB.setLocationRelativeTo(null);
        UB.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void xpenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpenggunaActionPerformed
        // TODO add your handling code here:
        User us=new User();
        us.setLocationRelativeTo(null);
        us.setVisible(true);
    }//GEN-LAST:event_xpenggunaActionPerformed

    private void penjualanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanBTActionPerformed
        // TODO add your handling code here:
        Penjualan PJ=new Penjualan();
        PJ.setLocationRelativeTo(null);
        PJ.setVisible(true);
    }//GEN-LAST:event_penjualanBTActionPerformed

    private void xpembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpembelianActionPerformed
        // TODO add your handling code here:
        Pembelian PB=new Pembelian();
        PB.setLocationRelativeTo(null);
        PB.setVisible(true);
    }//GEN-LAST:event_xpembelianActionPerformed

    private void xsuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xsuplierActionPerformed
        // TODO add your handling code here:
        Supplier SU=new Supplier();
        SU.setLocationRelativeTo(null);
        SU.setVisible(true);
    }//GEN-LAST:event_xsuplierActionPerformed

    private void barangBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangBTActionPerformed
        // TODO add your handling code here:
        Barang BR=new Barang();
        BR.setLocationRelativeTo(null);
        BR.setVisible(true);
    }//GEN-LAST:event_barangBTActionPerformed

    private void xbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xbarangActionPerformed
        // TODO add your handling code here:
        Barang BR=new Barang();
        BR.setLocationRelativeTo(null);
        BR.setVisible(true);
    }//GEN-LAST:event_xbarangActionPerformed

    private void pembelianBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianBTActionPerformed
        // TODO add your handling code here:
        Pembelian PB=new Pembelian();
        PB.setLocationRelativeTo(null);
        PB.setVisible(true);
    }//GEN-LAST:event_pembelianBTActionPerformed

    private void xpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xpenjualanActionPerformed
        // TODO add your handling code here:
        Penjualan PJ=new Penjualan();
        PJ.setLocationRelativeTo(null);
        PJ.setVisible(true);
    }//GEN-LAST:event_xpenjualanActionPerformed

    private void penjualanxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanxActionPerformed
        // TODO add your handling code here:
        lapPenjualan LP=new lapPenjualan();
        LP.setLocationRelativeTo(null);
        LP.setVisible(true);
    }//GEN-LAST:event_penjualanxActionPerformed

    private void suplierBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suplierBTActionPerformed
        // TODO add your handling code here:
        Supplier SU=new Supplier();
        SU.setLocationRelativeTo(null);
        SU.setVisible(true);
    }//GEN-LAST:event_suplierBTActionPerformed

    private void logoutBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTActionPerformed
        // TODO add your handling code here:
        Login LG=new Login();
        LG.setLocationRelativeTo(null);
        LG.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutBTActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        About ab=new About();
        ab.setLocationRelativeTo(null);
        ab.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangBT;
    private javax.swing.JMenuItem barangx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel loginJL;
    private javax.swing.JButton logoutBT;
    private javax.swing.JButton pembelianBT;
    private javax.swing.JButton penjualanBT;
    private javax.swing.JMenuItem penjualanx;
    private javax.swing.JButton suplierBT;
    private javax.swing.JLabel userJl;
    private javax.swing.JMenuItem xbarang;
    private javax.swing.JMenu xlap;
    private javax.swing.JMenuItem xlappembelian;
    private javax.swing.JMenuItem xlogout;
    private javax.swing.JMenu xmaster;
    private javax.swing.JMenuItem xpembelian;
    private javax.swing.JMenuItem xpengguna;
    private javax.swing.JMenuItem xpenjualan;
    private javax.swing.JMenuItem xsuplier;
    private javax.swing.JMenu xtrans;
    // End of variables declaration//GEN-END:variables
}
