/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class User extends javax.swing.JFrame {
    Connection conn;
    Statement st;
    ResultSet rs;

    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        bersih();
        tombolNormal();
        siapIsi(false);
    }
    
    private void bersih(){
        idTF.setText("");
        usernameTF.setText("");
        namaTF.setText("");
        aksesCB.setSelectedItem(null);
        passwordTF.setText("");
    }
    
    private void siapIsi(boolean a){
        idTF.setEnabled(a);
        usernameTF.setEnabled(a);
        namaTF.setEnabled(a);
        aksesCB.setEnabled(a);
        passwordTF.setEnabled(a);
    }
    
    private void tombolNormal(){
        tambahBT.setEnabled(true);
        simpanBT.setEnabled(false);
        hapusBT.setEnabled(false);
        editBT.setEnabled(false);
        cariBT.setEnabled(true);
    }
    
    private void simpan(){
        try{
            setKoneksi();
            String sql="insert into tbuser values('"+ idTF.getText() +"','" + usernameTF.getText()+"','" + namaTF.getText()
                + "','" + passwordTF.getText() + "','" + aksesCB.getSelectedItem() +"')";
            st.executeUpdate(sql); 
            JOptionPane.showMessageDialog(null,"Simpan pengguna berhasil");
            }
            catch (Exception e) {
        }
    }
    
    private void hapus(){
        try{
            String sql="delete from tbuser where noid='"+ idTF.getText() +"'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Hapus data sukses");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        tombolNormal();
    }
    
    private void perbarui(){
    try{
        setKoneksi();
            String sql="update tbuser set username='"+usernameTF.getText()+"',nama='"+namaTF.getText()+
            "',hakakses='"+aksesCB.getSelectedItem()+"' where noid='"+idTF.getText()+"'";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Edit data berhasil","Abadi Sport",JOptionPane.INFORMATION_MESSAGE);
        } 
        catch(Exception e){
        }
    }
    
    private void otomatis(){
         try {
            setKoneksi();
        String sql="select right (noid,2)+1 from tbuser";
        ResultSet rs=st.executeQuery(sql);
        usernameTF.setText("");
        namaTF.setText("");
        passwordTF.setText("");
        if(rs.next()){
            rs.last();
            String no=rs.getString(1);
            while (no.length()<3){
                no="0"+no;
                idTF.setText("U"+no);}
            }
        else
        {
            idTF.setText("U001"); 
        }
        } catch (Exception e) 
        {
    }                              
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        aksesCB = new javax.swing.JComboBox<>();
        passwordTF = new javax.swing.JPasswordField();
        namaTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        cariBT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tambahBT = new javax.swing.JButton();
        simpanBT = new javax.swing.JButton();
        editBT = new javax.swing.JButton();
        hapusBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(java.awt.Color.red);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)));
        jPanel3.setMinimumSize(new java.awt.Dimension(10, 80));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DATA PENGGUNA");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 196, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("ID Pengguna");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel10.setText("Password");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Hak Akses");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        aksesCB.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        aksesCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemilik", "Kasir", "Persediaan" }));
        jPanel1.add(aksesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 20));

        passwordTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 250, -1));

        namaTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        namaTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTFActionPerformed(evt);
            }
        });
        jPanel1.add(namaTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, -1));

        usernameTF.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, -1));

        idTF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        idTF.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        jPanel1.add(idTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 68, 168, -1));

        cariBT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Cari2.png"))); // NOI18N
        cariBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBTActionPerformed(evt);
            }
        });
        jPanel1.add(cariBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 68, 37, 20));

        jPanel2.setBackground(java.awt.Color.red);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tambahBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tambahBT.setText("Tambah");
        tambahBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBTActionPerformed(evt);
            }
        });
        jPanel2.add(tambahBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        simpanBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        simpanBT.setText("Simpan");
        simpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBTActionPerformed(evt);
            }
        });
        jPanel2.add(simpanBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, -1));

        editBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        editBT.setText("Edit");
        editBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBTActionPerformed(evt);
            }
        });
        jPanel2.add(editBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 90, -1));

        hapusBT.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        hapusBT.setText("Hapus");
        hapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBTActionPerformed(evt);
            }
        });
        jPanel2.add(hapusBT, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 80, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 350, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTFActionPerformed

    private void cariBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBTActionPerformed
        // TODO add your handling code here:
        String cari = JOptionPane.showInputDialog(null, "Cari berdasarkan ID Pengguna", "Input", JOptionPane.QUESTION_MESSAGE);
        setKoneksi();
        String sql="select * from tbuser where noid='"+ cari +"'";
        try {
            ResultSet rs=st.executeQuery(sql);
            if (rs.next())
            {
                idTF.setText(rs.getString(1));
                usernameTF.setText(rs.getString(2));
                namaTF.setText(rs.getString(3));
                passwordTF.setText(rs.getString(4));
                aksesCB.setSelectedItem(rs.getString(5));
                //button
                hapusBT.setEnabled(true);
                editBT.setEnabled(true);
            }
            else {
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cariBTActionPerformed

    private void tambahBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBTActionPerformed
        // TODO add your handling code here:
        if(tambahBT.getText().equalsIgnoreCase("tambah")){
            tambahBT.setText("Batal");
            bersih();
            siapIsi(true);
            otomatis();
            usernameTF.requestFocus();
            idTF.setEnabled(false);
            tambahBT.setEnabled(true);
            simpanBT.setEnabled(true);
            hapusBT.setEnabled(false);
            editBT.setEnabled(false);
            //keluarBT.setEnabled(false);
            cariBT.setEnabled(false);
        } else{
            tambahBT.setText("Tambah");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_tambahBTActionPerformed

    private void simpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBTActionPerformed
        // TODO add your handling code here:
        if(idTF.getText().isEmpty() || usernameTF.getText().isEmpty() || namaTF.getText().isEmpty() ||
            passwordTF.getText().isEmpty() || aksesCB.toString().equals(null)){
            JOptionPane.showMessageDialog(null, "Lengkapi inputan data","Abadi Sport",JOptionPane.INFORMATION_MESSAGE);
        } else{
            if(tambahBT.getText().equalsIgnoreCase("batal")){
                if(tambahBT.getText().equalsIgnoreCase("batal")){
                    simpan();
                } else{
                    JOptionPane.showMessageDialog(null, "Simpan data gagal, periksa kembali","Abadi Sport",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            if(editBT.getText().equalsIgnoreCase("batal")){
                if(editBT.getText().equalsIgnoreCase("batal")){
                    perbarui();
                } else{
                    JOptionPane.showMessageDialog(null, "Edit data gagal, periksa kembali","Abadi Sport",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            bersih();
            siapIsi(false);
            tambahBT.setText("Tambah");
            editBT.setText("Edit");
            tombolNormal();
        }
    }//GEN-LAST:event_simpanBTActionPerformed

    private void editBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBTActionPerformed
        // TODO add your handling code here:
        if(editBT.getText().equalsIgnoreCase("edit")){
            editBT.setText("Batal");
            siapIsi(true);
            //kodeTF.setEnabled(false);
            namaTF.requestFocus();
            tambahBT.setEnabled(false);
            simpanBT.setEnabled(true);
            hapusBT.setEnabled(false);
            editBT.setEnabled(true);
            //keluarBT.setEnabled(false);
            cariBT.setEnabled(false);
        } else{
            editBT.setText("Edit");
            bersih();
            siapIsi(false);
            tombolNormal();
        }
    }//GEN-LAST:event_editBTActionPerformed

    private void hapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBTActionPerformed
        // TODO add your handling code here:
        int pesan=JOptionPane.showConfirmDialog(null, "Yakin data akan dihapus ?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(pesan==JOptionPane.YES_OPTION){
            if(pesan==JOptionPane.YES_OPTION){
                hapus();
                bersih();
            } else{
                JOptionPane.showMessageDialog(null, "Hapus data gagal");
            }
        }
    }//GEN-LAST:event_hapusBTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ImageIcon img = new ImageIcon("src/gambar/kredit.png");
        setIconImage(img.getImage());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aksesCB;
    private javax.swing.JButton cariBT;
    private javax.swing.JButton editBT;
    private javax.swing.JButton hapusBT;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField namaTF;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton simpanBT;
    private javax.swing.JButton tambahBT;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables

    public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/db_tb_umar","root","TRPL2k19");
            st=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }
}
